# Generated by Django 3.1.4 on 2021-01-05 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchRider',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('revenue', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('flw_json', models.JSONField()),
                ('amount_charged', models.IntegerField(default=0)),
                ('processing_fee', models.IntegerField(default=0)),
                ('jumga_fee', models.IntegerField(default=0)),
                ('amount_paid', models.IntegerField(default=0)),
                ('created', models.DateTimeField(editable=False)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('shop_name', models.CharField(default='', max_length=255, unique=True)),
                ('revenue', models.IntegerField(default=0)),
                ('dispatch_rider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.dispatchrider')),
            ],
        ),
    ]
