# Generated by Django 3.1.4 on 2021-01-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispatchrider',
            old_name='revenue',
            new_name='current_revenue',
        ),
        migrations.RenameField(
            model_name='merchant',
            old_name='revenue',
            new_name='current_revenue',
        ),
        migrations.AddField(
            model_name='dispatchrider',
            name='total_revenue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dispatchrider',
            name='withdrawn_revenue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='merchant',
            name='total_revenue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='merchant',
            name='withdrawn_revenue',
            field=models.IntegerField(default=0),
        ),
    ]
