# Generated by Django 3.1.4 on 2021-01-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210109_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
